# Uncomment the next line to define a global platform for your project


target 'WeatherLook_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherLook_iOS
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Moya/RxSwift'
    pod 'SnapKit'
    pod 'Kingfisher'

  target 'WeatherLook_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherLook_iOSUITests' do
    # Pods for testing
  end

end
